/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.gui;

import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Pravesh
 */
public class viewScoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form viewScoreFrame
     */
    public viewScoreFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
        txtHello.setText("Hello  "+loginFrame.uname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtLogOut = new javax.swing.JLabel();
        txtHello = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jrbViewStudent = new javax.swing.JRadioButton();
        jrbViewAll = new javax.swing.JRadioButton();
        jrbDoTask = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        txtLogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLogOut.setForeground(new java.awt.Color(255, 153, 51));
        txtLogOut.setText("Log Out");
        txtLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLogOutMouseEntered(evt);
            }
        });

        txtHello.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHello.setForeground(new java.awt.Color(255, 153, 51));
        txtHello.setText("Hello");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("VIEW SCORES PANEL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Make A Choice");

        buttonGroup1.add(jrbViewStudent);
        jrbViewStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbViewStudent.setForeground(new java.awt.Color(255, 153, 51));
        jrbViewStudent.setText("View Score Of A SIngle Student");
        jrbViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbViewStudentActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbViewAll);
        jrbViewAll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbViewAll.setForeground(new java.awt.Color(255, 153, 51));
        jrbViewAll.setText("View AllScores");

        jrbDoTask.setBackground(new java.awt.Color(0, 0, 0));
        jrbDoTask.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbDoTask.setForeground(new java.awt.Color(255, 153, 51));
        jrbDoTask.setText("Do Task");
        jrbDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDoTaskActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 153, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Java Project\\stud1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHello)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtLogOut)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbViewStudent)
                            .addComponent(jrbViewAll))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbDoTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogOut)
                    .addComponent(txtHello))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jrbViewStudent)
                        .addGap(18, 18, 18)
                        .addComponent(jrbViewAll)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbDoTask)
                            .addComponent(btnBack)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogOutMouseClicked
        // TODO add your handling code here:
         dispose();
        loginFrame lFrame=new loginFrame();
        lFrame.setVisible(true);
    }//GEN-LAST:event_txtLogOutMouseClicked

    private void txtLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogOutMouseEntered
        // TODO add your handling code here:
        Font f=new Font("Tahoma",Font.ITALIC,14);
        txtLogOut.setFont(f);
    }//GEN-LAST:event_txtLogOutMouseEntered

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        adminOptionsFrame adminFrame=new adminOptionsFrame();
        adminFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jrbViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbViewStudentActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jrbViewStudentActionPerformed

    private void jrbDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDoTaskActionPerformed
        // TODO add your handling code here:
        if(validateInputs()==false)
        {
            JOptionPane.showMessageDialog(null,"Please Select Any Option","EMPTY",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
        if(jrbViewStudent.isSelected())
        {
        singleStudentScoreFrame singleScoreFrame=new singleStudentScoreFrame();
        singleScoreFrame.setVisible(true);
        this.dispose();
        }
        if(jrbViewAll.isSelected())
        {
        viewAllStudentScore viewAllScore=new viewAllStudentScore();
        viewAllScore.setVisible(true);
        this.dispose();  
        }
        }
    }//GEN-LAST:event_jrbDoTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewScoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jrbDoTask;
    private javax.swing.JRadioButton jrbViewAll;
    private javax.swing.JRadioButton jrbViewStudent;
    private javax.swing.JLabel txtHello;
    private javax.swing.JLabel txtLogOut;
    // End of variables declaration//GEN-END:variables
 private boolean validateInputs()
 {
     if((jrbViewStudent.isSelected()==false&&jrbViewAll.isSelected()==false))
      return false;
     else
         return true;
                 
    }
}

